package com.shailendra.smart_player.util

/**
 * Created by Shailendra on 29-07-2021
 * */
object Constants {

    const val ANALYTICS_CUSTOM_EVENT_VIDEO_PLAYBACK = "Video Playback"

    // Player Analytics Playback States
    const val ANALYTICS_ACTION_VIDEO_PLAYBACK_STARTED = "PLAYBACK_STARTED"
    const val ANALYTICS_ACTION_VIDEO_PLAYBACK_RESUMED_FROM_PREVIOUSLY_ABANDONED_PLAYBACK = "PLAYBACK_RESUMED_FROM_PREVIOUSLY_ABANDONED_PLAYBACK"
    const val ANALYTICS_ACTION_VIDEO_PLAYBACK_RESUMED_AFTER_SEEK = "PLAYBACK_RESUMED_AFTER_SEEK"
    const val ANALYTICS_ACTION_FATAL_PLAYER_ERROR = "FATAL_PLAYER_ERROR"
    const val ANALYTICS_ACTION_VIDEO_PLAYBACK_ABANDONED = "PLAYBACK_ABANDONED"
    const val ANALYTICS_ACTION_DROPPED_VIDEO_FRAMES = "DROPPED_VIDEO_FRAMES"
    const val ANALYTICS_ACTION_MEAN_NETWORK_BANDWIDTH = "MEAN_NETWORK_BANDWIDTH"
    const val ANALYTICS_ACTION_PLAYBACK_WATCHED = "PLAYBACK_WATCHED_"
    const val ANALYTICS_ACTION_PLAYBACK_COMPLETED = "PLAYBACK_COMPLETED"

    const val MAX_GESTURE_LENGTH = 0.75f

}